<script setup lang="ts">
const mathStore = useMathStore()
const { config, questions } = storeToRefs(mathStore)

// Initial generation
onMounted(() => {
  if (questions.value.length === 0) {
    mathStore.generate()
  }
})

// Dynamic grid classes
const gridColsClass = computed(() => {
  switch (config.value.layout.columns) {
    case 2: return 'grid-cols-2'
    case 4: return 'grid-cols-4'
    default: return 'grid-cols-3'
  }
})

const fontSizeClass = computed(() => {
  switch (config.value.layout.fontSize) {
    case 'sm': return 'text-xl'
    case 'lg': return 'text-3xl'
    default: return 'text-2xl'
  }
})

// Helper to slice questions for each page
function getPageQuestions(page: number) {
  const perPage = mathStore.questionsPerPage
  const verifiedPerPage = Math.max(1, perPage) // Safety check
  const start = (page - 1) * verifiedPerPage
  const end = start + verifiedPerPage
  return questions.value.slice(start, end)
}
</script>

<template>
  <!-- Question Sheets -->
  <template v-for="page in config.layout.totalPages" :key="`q-page-${page}`">
    <div
      class="print-sheet mx-auto my-8 bg-white flex flex-col shadow-2xl overflow-hidden print:m-0 print:w-full print:shadow-none"
      :style="{
        width: '210mm',
        height: '297mm',
        padding: '20mm',
      }"
    >
      <!-- Header -->
      <header class="mb-8 pb-4 border-b-2 border-black flex items-end justify-between">
        <div>
          <h1 class="text-2xl text-black tracking-widest font-bold">
            数学口算练习
          </h1>
        </div>
        <div class="text-sm flex gap-8">
          <div>
            姓名: 
            <span v-if="config.layout.studentName" class="font-bold underline underline-offset-4 decoration-black min-w-[3em] inline-block text-center">{{ config.layout.studentName }}</span>
            <span v-else>______</span>
          </div>
          <div>第 {{ page }} / {{ config.layout.totalPages }} 页</div>
          <div>对题: ______ 道</div>
          <div>用时: ______ 分</div>
        </div>
      </header>

      <!-- Questions Grid -->
      <div
        class="mb-8 flex-1 grid content-start"
        :class="gridColsClass"
        :style="{
          columnGap: `${config.layout.horizontalGap * 0.5}rem`,
          rowGap: `${config.layout.verticalGap * 0.5}rem`,
        }"
      >
        <div
          v-for="q in getPageQuestions(page)"
          :key="q.id"
          class="flex items-center"
          :class="fontSizeClass"
        >
          <!-- Cell-Based Equation Row -->
          <div
            class="equation-row text-black tracking-wide font-medium font-mono whitespace-nowrap"
          >
            <!-- Term 1 -->
            <span class="cell-number" :class="{ 'write-mode': q.hideTermIndex === 0 }">
              <template v-if="q.hideTermIndex !== 0">{{ q.terms[0] }}</template>
            </span>

            <!-- Op 1 -->
            <span class="cell-symbol">{{ q.operators[0] }}</span>

            <!-- Term 2 -->
            <span class="cell-number" :class="{ 'write-mode': q.hideTermIndex === 1 }">
              <template v-if="q.hideTermIndex !== 1">{{ q.terms[1] }}</template>
            </span>

            <!-- Op 2 & Term 3 (if exists) -->
            <template v-if="config.logic.termCount === 3">
              <span class="cell-symbol">{{ q.operators[1] }}</span>
              <span class="cell-number" :class="{ 'write-mode': q.hideTermIndex === 2 }">
                <template v-if="q.hideTermIndex !== 2">{{ q.terms[2] }}</template>
              </span>
            </template>

            <!-- Equals -->
            <span class="cell-symbol">=</span>

            <!-- Result -->
            <span class="cell-result" :class="{ 'write-mode': q.hideTermIndex === undefined }">
              <template v-if="q.hideTermIndex !== undefined">{{ q.result }}</template>
            </span>
          </div>
        </div>
      </div>

      <!-- Footer -->
      <footer class="text-xs text-gray-400 mt-auto pt-4 border-t-2 border-black flex justify-between">
        <div>Generated by SmartMath Print</div>
        <div>{{ new Date().toLocaleDateString() }}</div>
      </footer>
    </div>
  </template>

  <!-- Answer Sheets -->
  <template v-if="config.layout.showAnswers">
    <template v-for="page in config.layout.totalPages" :key="`a-page-${page}`">
      <div
        class="print-sheet mx-auto my-8 bg-white flex flex-col shadow-2xl overflow-hidden print:m-0 print:w-full print:shadow-none"
        :style="{
          width: '210mm',
          height: '297mm',
          padding: '20mm',
        }"
      >
        <!-- Header -->
        <header class="mb-8 pb-4 border-b-2 border-black flex items-end justify-between">
          <div>
            <h1 class="text-2xl text-black tracking-widest font-bold">
              参考答案
            </h1>
            <p class="text-xs text-gray-500 mt-1 print:hidden">
              Answer Key (Page {{ page }})
            </p>
          </div>
          <div class="text-sm text-gray-500">
            {{ new Date().toLocaleDateString() }}
          </div>
        </header>

        <!-- Answers Grid -->
        <div
          class="flex-1 grid content-start"
          :class="gridColsClass"
          :style="{
            columnGap: `${config.layout.horizontalGap * 0.5}rem`,
            rowGap: `${config.layout.verticalGap * 0.5}rem`,
          }"
        >
          <div
            v-for="q in getPageQuestions(page)"
            :key="q.id"
            class="flex items-center"
            :class="fontSizeClass"
          >
            <!-- Cell-Based Equation Row (Answer Sheet) -->
            <div
              class="equation-row text-gray-600 tracking-wide font-medium font-mono whitespace-nowrap"
            >
              <!-- Term 1 -->
              <span class="cell-number" :class="{ 'text-black font-bold': q.hideTermIndex === 0 }">
                {{ q.terms[0] }}
              </span>

              <!-- Op 1 -->
              <span class="cell-symbol">{{ q.operators[0] }}</span>

              <!-- Term 2 -->
              <span class="cell-number" :class="{ 'text-black font-bold': q.hideTermIndex === 1 }">
                {{ q.terms[1] }}
              </span>

              <!-- Op 2 & Term 3 (if exists) -->
              <template v-if="config.logic.termCount === 3">
                <span class="cell-symbol">{{ q.operators[1] }}</span>
                <span class="cell-number" :class="{ 'text-black font-bold': q.hideTermIndex === 2 }">
                  {{ q.terms[2] }}
                </span>
              </template>

              <!-- Equals -->
              <span class="cell-symbol">=</span>

              <!-- Result -->
              <span
                class="cell-result"
                :class="{ 'text-black font-bold': q.hideTermIndex === undefined }"
              >
                {{ q.result }}
              </span>
            </div>
          </div>
        </div>

        <!-- Footer -->
        <footer class="text-xs text-gray-500 mt-auto pt-4 border-t-2 border-black flex justify-between">
          <div>Generated by SmartMath Print</div>
          <div>Page {{ page }} (Answers)</div>
        </footer>
      </div>
    </template>
  </template>
</template>

<style scoped>
@media print {
  @page {
    size: A4;
    margin: 0; /* Important: remove default browser margins */
  }

  body {
    margin: 0;
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
  }

  .print-sheet {
    box-shadow: none;
    margin: 0;
    width: 210mm; /* Strict A4 Width */
    height: 297mm; /* Strict A4 Height */
    padding: 20mm !important; /* Fixed physical padding */
    page-break-after: always;
    page-break-inside: avoid;
    overflow: hidden; /* Prevent spillover */
  }

  .print-sheet:last-child {
    page-break-after: auto;
    margin-bottom: 0;
  }
}

/* --- Cell-Based Layout System --- */

.equation-row {
  display: flex;
  align-items: center;
  /* Ensure it takes full width of its grid column */
  width: 100%;
}

.cell-number {
  width: 1.2em; /* Fixed width needed for vertical alignment of operators */
  height: 1.1em;
  flex-shrink: 0;
  text-align: right;
  display: flex;
  justify-content: flex-end;
  align-items: center;
}

/* Intersection Selector / Modifier for Write Mode */
.cell-number.write-mode,
.cell-result.write-mode {
  border: 1px solid black;
  border-radius: 0.1em;
  /* Width is inherited from base class */
}

.cell-symbol {
  width: 0.5em; /* Fixed width */
  flex-shrink: 0;
  text-align: center;
  display: flex;
  justify-content: center;
  align-items: center;
}

.cell-result {
  width: 1.2em; /* Fixed width matching number cell */
  height: 1.1em;
  text-align: left;
  display: flex;
  justify-content: flex-start;
  align-items: center;
  padding-left: 0.1em; /* Tiny padding */
  margin-left: 0.1em;
}
</style>
